<?php

namespace Ositel\TransactionBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;
use Ositel\TransactionBundle\Entity\Category;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $params
     *
     * @return array
     */
    public function search(array $params): array
    {
        $queryBuilder = $this->createQueryBuilder('t')
            ->select('t')
            ->leftJoin(Category::class, 'c', Join::WITH, 't.category = c.id')
            ->where('t.isOutput = :output')
            ->setParameter('output', true)
        ;

        if (!empty($params['title'])) {
            $queryBuilder->andWhere('t.title like :title')
                ->setParameter('title', sprintf('%%%s%%', $params['title']));
        }

        if (!empty($params['amount'])) {
            $queryBuilder->andWhere('t.amount = :amount')
                ->setParameter('amount', $params['amount']);
        }

        if (!empty($params['isValid'])) {
            $queryBuilder->andWhere('t.isValid = :isValid')
                ->setParameter('isValid', $params['isValid']);
        }

        if (!empty($params['category'])) {
            $queryBuilder->andWhere('t.category = :category')
                ->setParameter('category', $params['category']);
        }

        return $queryBuilder->getQuery()->execute();
    }

    public function filter(array $params): array
    {
        $queryBuilder = $this->createQueryBuilder('t')
            ->select('t')
            ->where('MONTH(t.createdAt) = :month')
            ->andWhere('YEAR(t.createdAt) = :year')
            ->setParameter('month', $params['month'])
            ->setParameter('year', $params['year']);

        return $queryBuilder->getQuery()->getArrayResult();
    }
}
